apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: hello-world-action
description: its just a hello-world-action

runs:
  using: composite
  steps:
    - id: hello-world
      name: helloworld
      uses: docker://alpine/helm:latest
      shell: sh
      run: |
        cd /var
        ls -al
         
